---
# By default egress traffic is not allowed, define below the ports allowed.
egress:
  - ports:
      - protocol: TCP
        port: 443
  - ports:
      - protocol: TCP
        port: 80
    to:
      - podSelector:
          matchLabels:
            kubevirt.io: virt-launcher
