---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: containerview
        ports:
          - port: 8000
            protocol: TCP
            targetPort: 8000
            name: adminer
    routes:
      - name: containerview
        host: containerview
        service: containerview
        targetPort: 8000
        tls: true
        tls_termination: Edge