---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
          - name: httpd
            ports:
              - port: 80
                protocol: TCP
                targetPort: 80
                name: httpd
    routes:
          - name: httpd
            host: httpd
            service: httpd
            targetPort: 80
            tls: true
            tls_termination: Edge